### ISSUE TITLE
Discarding the original robots.txt files from the repository

### ISSUE THREAD

**Issue by maaaaz** [danielmiessler/RobotsDisallowed#1]
Hello Daniel,

Thank for your this nice project, `robots.txt` entries are always gold for an attacker. 

But cloning this repo takes a lot of time and resources because the raw original `robots.txt` file for each top Alexa site is included: could it be possible to discard them from that repo, in order to only have the root `Top*-RobotsDisallowed.txt` files ?

**Comment by danielmiessler** [comment]
I've removed them, thank you for pointing that out.
